### ISSUE TITLE
Consolidate FontAwesome dependencies

### ISSUE THREAD

**Issue by ghost** [dlsc-software-consulting-gmbh/PreferencesFX#309]
PreferencesFX uses both [ControlsFX](https://github.com/controlsfx/controlsfx) and [FontAwesomeFX](https://bitbucket.org/Jerady/fontawesomefx/src/master/). ControlsFX provides a thin wrapper for the [FontAwesome TrueType Font](https://github.com/controlsfx/controlsfx/blob/master/controlsfx/src/main/java/org/controlsfx/glyphfont/FontAwesome.java). As far as I can tell, PreferencesFX doesn't use fonts specific to FontAwesomeFX.

As a consequence, projects that use PreferencesFX will get two copies of "fontawesome-webfont.ttf":

```
165548 Sun Nov 01 13:43:28 PST 2020 org/controlsfx/glyphfont/fontawesome-webfont.ttf
 99468 Sat Jan 12 20:40:14 PST 2019 de/jensd/fx/glyphs/fontawesome/fa-brands-400.ttf
 30560 Sat Jan 12 20:40:14 PST 2019 de/jensd/fx/glyphs/fontawesome/fa-regular-400.ttf
114928 Sat Jan 12 20:40:14 PST 2019 de/jensd/fx/glyphs/fontawesome/fa-solid-900.ttf
165548 Sat Jan 12 20:40:14 PST 2019 de/jensd/fx/glyphs/fontawesome/fontawesome-webfont.ttf
```

After refactoring [KeenWrite](https://github.com/DaveJarvis/keenwrite) in an attempt to consolidate the TTF files (i.e., I removed all references to FontAwesomeFX in favour of using ControlsFX exclusively), I was surprised to see FontAwesomeFX still in use. Gradle's dependency trace showed that PreferencesFX had the two references.

What do you think of revising PreferencesFX to use only the version of FontAwesome icons that is bundled with ControlsFX to avoid duplication?

**Comment by dlemmermann** [comment]
Actually I am inclined to move away from FontAwesomeFX and use Ikonli instead. This is the library of choice for icons for all of my projects.

**Comment by dlemmermann** [comment]
Removed FontawesomeFX.

**Comment by ghost** [comment]
> Ikonli

I don't suppose this could be a build option? My main point was that the font icons were duplicated. Switching from FontAwesomeFX to Ikonli is still duplicating fonts, architecturally: one set for ControlsFX and another set for PreferencesFX. I was looking to reduce the size of the final `.jar` file by consolidating different font resources.

Another possibility would be to switch ControlsFX (and my application) to use Ikonli, but that seems like a lot of effort and project coordination to work around this particular decision.

Your thoughts?

**Comment by dlemmermann** [comment]
All of my projects use Ikonli and I do not care much about what ControlsFX uses. But we could make an exception in this case because there are only two icons used anyways: for the undo / redo buttons. If you want to you can submit a PR that changes that. Ideally very soon because on May 1st this project's build pipeline breaks because of bintray stopping its services.

**Comment by shoaniki** [comment]
Annnd it's happened, just tried to add PreferencesFX to my project and I can't because FontAwesomeFX was only on jcenter.  Please consider making a release without that dependency.

(If this project really only requires two icons, might it be possible to mark the font dependency as optional and let applications provide their own icons if they want?)
