### ISSUE TITLE
Show() cannot be called twice?

### ISSUE THREAD

**Issue by ArvidNy** [dlsc-software-consulting-gmbh/PreferencesFX#80]
I've just been trying out the new release and I'm really grateful for the additions that have been made for this release! However, as far as I can tell the PreferenceFXDialog cannot be closed and reopened with the current code, since modality is always set on show() but the modality cannot be reassigned if it's already been shown:

```
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: Cannot set modality once stage has been set visible
	at javafx.stage.Stage.initModality(Stage.java:525)
	at javafx.scene.control.HeavyweightDialog.initModality(HeavyweightDialog.java:132)
	at javafx.scene.control.Dialog.initModality(Dialog.java:438)
	at com.dlsc.preferencesfx.view.PreferencesFxDialog.show(PreferencesFxDialog.java:71)
	at com.dlsc.preferencesfx.PreferencesFx.show(PreferencesFx.java:143)
	at com.dlsc.preferencesfx.PreferencesFx.show(PreferencesFx.java:134)
```

Please correct me if I'm missing something here.

**Comment by martinfrancois** [comment]
Hi @ArvidNy
Thanks for the praise!
Which JDK are you using, which OS and which version of PreferencesFX?
I noticed this behavior under Java 11, which is why I made a fix (https://github.com/dlsc-software-consulting-gmbh/PreferencesFX/commit/c32cb6753dce1a98726437a8ee06c99a1f9b763f), which is included in the 11.3.0 release. I didn't observe this behavior with Java 8, which is why I only applied the fix there. But maybe there are certain circumstances that are not covered yet...

**Comment by ArvidNy** [comment]
Manjaro Linux, the most recent release of PreferencesFX for Java 8 and JDK 8 (1.8.0_202-b08). Just noticed that there's a more recent version of Java that I haven't tried so that might be it. Won't be able to check in a couple of days however.

**Comment by martinfrancois** [comment]
Hi @ArvidNy 
Thanks for reporting back!
I just fixed the issue in the Java 8 branch as well and created a release with version `8.3.2`. It's available on Bintray as of now and should be available from Maven Central in about 2 hours.
Please try it and report back, if it worked for you.

**Comment by ArvidNy** [comment]
Seems to be working now, thanks!
